server:
  port: 9006
spring:
  application:
    name: goods
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  profiles:
    active: myq
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:   #配置全局的feign的调用超时时间  如果 有指定的服务配置 默认的配置不会生效
        connectTimeout: 60000 # 指定的是 消费者 连接服务提供者的连接超时时间 是否能连接  单位是毫秒
        readTimeout: 20000  # 指定的是调用服务提供者的 服务 的超时时间（）  单位是毫秒
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: true
        isolation:
          strategy: SEMAPHORE
          thread:
            # 熔断器超时时间，默认：1000/毫秒
            timeoutInMilliseconds: 20000
mybatis-plus:
  mapper-locations: mapper/*.xml
  configuration:
    # 设置启用数据库字段下划线映射到java对象的驼峰式命名属性，默认为false （ 注意如果返回类型是HashMap会使驼峰标识失效）
    map-underscore-to-camel-case: true
    # 打印sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.hj.entity

workerId: 1
datacenterId: 1

# 分页插件助手的配置
pagehelper:
  helper-dialect: MYSQL
  support-methods-arguments: true

# 日志级别
logging:
  level:
    root: info